#!/bin/sh

export PATH=/home/wanding/MATLAB/R2011a/bin:$PATH:/home/wanding/bin:/home/wanding/Dropbox/installed_programs/FASIMU_complete/FASIMU:$HOME/sync/installed_software/ncbi-blast-2.2.25+-src/c++/GCC443-Debug/bin:$HOME/sync/installed_software/gurobi/gurobi451/linux32/bin:$HOME/ibm/ILOG/CPLEX_Studio_Academic124/cplex/bin/x86_sles10_4.1
# export _JAVA_OPTIONS="-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
shopt -s cdspell

CDPATH='.:..:../..:~:~/Dropbox:~/Dropbox/project_hgt/:~/sync/project_HGT'
export BINA_HOME=/home/wanding/Dropbox/installed_programs/BiNA-1.3.1-07-FASIMU
export PYTHONPATH=$HOME/Dropbox/scripts/python/:/usr/lib/python2.6/site-packages
# export PERL5LIB="$HOME/bio/bioperl-live:$PERL5LIB"

export PATH=$PATH:/home/wanding/bin/fasimudir

# directories
SYNC=$HOME/sync
# export COMMUNITY_CLUSTER_DATA=/shared.scratch/wz4/data
# export COMMUNITY_DATA=$SYNC/project_community/data
# export COMMUNITY_DATA_LARGE=/media/ExternalDrivLarg/slowsync/community_data_large
# export COMMUNITY_FIGS=$SYNC/project_community/figs
# export COMMUNITY_DOWNLOADS=$SYNC/project_community/downloads
# export OPERON_DATA=$SYNC/project_operon/data
# export OPERON_FIGS=$SYNC/project_operon/figs
# export OPERON_DOWNLOADS=$SYNC/project_operon/downloads
export HGT_DATA=$SYNC/project_HGT/data
export HGT_DOWNLOADS=$SYNC/project_HGT/downloads
export HGT_FIGS=$SYNC/project_HGT/figs
# export EPISTASIS_DATA=$SYNC/project_epistasis/data
# export EPISTASIS_DOWNLOADS=$SYNC/project_epistasis/downloads
# export EPISTASIS_FIGS=$SYNC/project_epistasis/figs


EXTERNALDRIV=/media/ExternalDriv
SLOWSYNC=$EXTERNALDRIV/slowsync
export KEGGDIR=$SLOWSYNC/KEGG
export BLASTDBDIR=$SLOWSYNC/blastdb

# ibus
export XIM="ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
export XMODIFIERS="@im=ibus"
# /home/wanding/sync/installed_software/SBMLToolbox_3.1.2/toolbox:
export LD_LIBRARY_PATH=/home/wanding/libsbml/lib

export GUROBI_HOME="/home/wanding/gurobi501/linux64"
export PATH="${PATH}:${GUROBI_HOME}/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"

export ILOG_LICENSE_FILE=/home/wanding/Dropbox/config/access.ilm
# export R_HOME=/home/wanding/R_home

export PATH=$PATH:/home/wanding/bin
export SCREENRC=/home/wanding/Dropbox/config/screenrc/201311screenrc

# for SCREEN
case $TERM in
  screen*)
    SCREENTITLE='\[\ek\e\\\]\[\ek\W\e\\\]'
    ;;
  *)
    SCREENTITLE=''
    ;;
esac

function prompt {
  local BLACK="\[\033[0;30m\]"
  local BLACKBOLD="\[\033[1;30m\]"
  local RED="\[\033[0;31m\]"
  local REDBOLD="\[\033[1;31m\]"
  local GREEN="\[\033[0;32m\]"
  local GREENBOLD="\[\033[1;32m\]"
  local YELLOW="\[\033[0;33m\]"
  local YELLOWBOLD="\[\033[1;33m\]"
  local BLUE="\[\033[0;34m\]"
  local BLUEBOLD="\[\033[1;34m\]"
  local PURPLE="\[\033[0;35m\]"
  local PURPLEBOLD="\[\033[1;35m\]"
  local CYAN="\[\033[0;36m\]"
  local CYANBOLD="\[\033[1;36m\]"
  local GREY="\[\033[00m\]"
  local WHITE="\[\033[0;37m\]"
  local WHITEBOLD="\[\033[1;37m\]"
  export PS1="$REDBOLD[\t]${SCREENTITLE}$GREY[$GREENBOLD\u@\h $YELLOWBOLD\w$GREY]\$ "
  # export PS1="$BLACKBOLD[\t]${SCREENTITLE}[\[\033[01;32m\]\u@\h \[\033[01;34m\]\w\[\033[00m\]]\$ "
  # export PS1="\n$BLACKBOLD[\t]$GREENBOLD \u@\h\[\033[00m\]:$BLUEBOLD\w\[\033[00m\] \\$ "
}

prompt
