#!/bin/bash
# Source global definitions
 if [ -f /etc/bashrc ]; then
 	. /etc/bashrc
 fi

############# the following copied from /etc/bashrc ##############
# are we an interactive shell?
if [ "$PS1" ]; then
  if [ -z "$PROMPT_COMMAND" ]; then
    case $TERM in
    xterm*|vte*)
      if [ -e /etc/sysconfig/bash-prompt-xterm ]; then
          PROMPT_COMMAND=/etc/sysconfig/bash-prompt-xterm
      elif [ "${VTE_VERSION:-0}" -ge 3405 ]; then
          PROMPT_COMMAND="__vte_prompt_command"
      else
          PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
      fi
      ;;
    screen*)
      if [ -e /etc/sysconfig/bash-prompt-screen ]; then
          PROMPT_COMMAND=/etc/sysconfig/bash-prompt-screen
      else
          PROMPT_COMMAND='printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
      fi
      ;;
    *)
      [ -e /etc/sysconfig/bash-prompt-default ] && PROMPT_COMMAND=/etc/sysconfig/bash-prompt-default
      ;;
    esac
  fi
  # Turn on parallel history
  shopt -s histappend
  history -a
  # Turn on checkwinsize
  shopt -s checkwinsize
  [ "$PS1" = "\\s-\\v\\\$ " ] && PS1="[\u@\h \W]\\$ "
  # You might want to have e.g. tty in prompt (e.g. more virtual machines)
  # and console windows
  # If you want to do so, just add e.g.
  # if [ "$PS1" ]; then
  #   PS1="[\u@\h:\l \W]\\$ "
  # fi
  # to your custom modification shell script in /etc/profile.d/ directory
fi

if ! shopt -q login_shell ; then # We're not a login shell
    # Need to redefine pathmunge, it get's undefined at the end of /etc/profile
    pathmunge () {
        case ":${PATH}:" in
            *:"$1":*)
                ;;
            *)
                if [ "$2" = "after" ] ; then
                    PATH=$PATH:$1
                else
                    PATH=$1:$PATH
                fi
        esac
    }

    # By default, we want umask to get set. This sets it for non-login shell.
    # Current threshold for system reserved uid/gids is 200
    # You could check uidgid reservation validity in
    # /usr/share/doc/setup-*/uidgid file
    if [ $UID -gt 199 ] && [ "`id -gn`" = "`id -un`" ]; then
       umask 002
    else
       umask 022
    fi

    SHELL=/bin/bash
    # Only display echos from profile.d scripts if we are no login shell
    # and interactive - otherwise just process them to set envvars
    for i in /etc/profile.d/*.sh; do
      if [[ $i == *man.sh* ]]; then
        continue
      fi
        if [ -r "$i" ]; then
            if [ "$PS1" ]; then
                . "$i"
            else
                . "$i" >/dev/null
            fi
        fi
    done

    unset i
    unset -f pathmunge
fi


####################### my own settings ######################

module load uge
module load singularity/3.2.0

alias ls='ls --color'
alias rm='rm -i'
alias lc="wc -l"
alias ll="ls -l"
alias lv="ls -v"
alias rf="readlink -f"
alias parallel="parallel --gnu --progress"
alias du="du -sh"
alias st="qstat"
alias bs=". ~/.bashrc"
alias sr="screen -r"
alias wget="wget --limit-rate 4M"

export SCREENRC=/mnt/isilon/zhoulab/labtools/screenrc/screenrc_hp
export AWKPATH=/mnt/isilon/zhoulab/labtools/awkutils

export PATH=~/bin:$PATH
export PATH=/mnt/isilon/zhoulab/labbin:$PATH
export PATH=/mnt/isilon/zhoulab/labpipelines/pipelines:$PATH
export PATH=/mnt/isilon/zhoulab/labsoftware/valgrind/valgrind-3.15/bin:$PATH
# export JAVA_HOME=/primary/vari/software/java/jdk1.8.0_60

alias scp='rsync -Pravdtze ssh'
alias awk='awk -F"\t" -v OFS="\t"'
alias les="less -S"
alias qsubi='qlogin -q interactive.q'
alias qstatall='qstat -u "*" | less'
alias qstatallrun='qstat -u "*" -s r | less'
alias qhost='qhost | less'
alias qsuball="find pbs/ -type f -name '*.pbs' | sort | xargs -I {} qsub {}"
alias sort="LC_ALL=C sort"

### some convenience function to auto job submission

# change this if you want to just change the folder where pbs file is auto-generated
export PBSDIR=/mnt/isilon/zhoulab/tmp/pbs
# change this if you don't like the job name
export PBSROOT=LabJob
# change this if you want to explicitly control pbs file location
export PBSPATH=NA

## the following needs be ended with
## QSEND
## )"
alias qsub24='pbsgen one -dest $PBSPATH -pbs $PBSDIR -jobroot $PBSROOT -submit -ppn 24 "$(cat <<'"'"'QSEND'"'
" # 24-core job
alias qsub12='pbsgen one -dest $PBSPATH -pbs $PBSDIR -jobroot $PBSROOT -submit -ppn 12 "$(cat <<'"'"'QSEND'"'
" # 12-core job
alias qsub4='pbsgen one -dest $PBSPATH -pbs $PBSDIR -jobroot $PBSROOT -submit -ppn 4 "$(cat <<'"'"'QSEND'"'
" # 4-core job
alias qsub1='pbsgen one -dest $PBSPATH -pbs $PBSDIR -jobroot $PBSROOT -submit -ppn 1 "$(cat <<'"'"'QSEND'"'
" # 1-core job

## the following needs be ended with
## QSREND
## QSEND
## )"
alias qsubR24='pbsgen one -dest $PBSPATH -pbs $PBSDIR -jobroot $PBSROOT -submit -ppn 24 "$(cat <<'"'"'QSEND'"'"'
Rscript - <<'"'"'QSREND'"'
"
alias qsubR12='pbsgen one -dest $PBSPATH -pbs $PBSDIR -jobroot $PBSROOT -submit -ppn 12 "$(cat <<'"'"'QSEND'"'"'
Rscript - <<'"'"'QSREND'"'
"
alias qsubR4='pbsgen one -dest $PBSPATH -pbs $PBSDIR -jobroot $PBSROOT -submit -ppn 4 "$(cat <<'"'"'QSEND'"'"'
Rscript - <<'"'"'QSREND'"'
"
alias qsubR1='pbsgen one -dest $PBSPATH -pbs $PBSDIR -jobroot $PBSROOT -submit -ppn 1 "$(cat <<'"'"'QSEND'"'"'
Rscript - <<'"'"'QSREND'"'
"

# change this in your own .bashrc
export HPCUSERNAME="zhouw3"
function qdelall {
   qstat | grep $HPCUSERNAME | awk '{split($1,a,".");print a[1]}' | xargs -I {} qdel {}
}
function qdelrange {
  for ((i=$1;i<=$2;i++)); do qdel $i;done
}

function prompt {
  local BLACK="\[\033[0;30m\]"
  local BLACKBOLD="\[\033[1;30m\]"
  local GREY="\[\033[00m\]"
  local RED="\[\033[0;31m\]"
  local REDBOLD="\[\033[1;31m\]"
  local GREEN="\[\033[0;32m\]"
  local GREENBOLD="\[\033[1;32m\]"
  local YELLOW="\[\033[0;33m\]"
  local YELLOWBOLD="\[\033[1;33m\]"
  local BLUE="\[\033[0;34m\]"
  local BLUEBOLD="\[\033[1;34m\]"
  local PURPLE="\[\033[0;35m\]"
  local PURPLEBOLD="\[\033[1;35m\]"
  local CYAN="\[\033[0;36m\]"
  local CYANBOLD="\[\033[1;36m\]"
  local WHITE="\[\033[0;37m\]"
  local WHITEBOLD="\[\033[1;37m\]"
  # export PS1="$REDBOLD[\t]${SCREENTITLE}$GREY[$GREENBOLD\u@\h $YELLOWBOLD\w$GREY]"'$ '
  export PS1="$REDBOLD[\t]${SCREENTITLE}$GREY[$GREENBOLD\u@\h $YELLOWBOLD\w$GREY]\$ "

}

prompt

PROMPT_COMMAND='/bin/echo -ne "\033k\033\0134\033k[`basename ${PWD}`]\033\0134"'

case "$TERM" in
    screen*) PROMPT_COMMAND='echo -ne "\033k\033\0134"'
esac

## search wzprojects
function wzgrep {
  ag "$1" /mnt/isilon/zhoulab/labjournal --pager="less -R"
}

function wzfind {
  find /mnt/isilon/zhoulab/labjournal -name "*$1*" | fzf
}

function mkdircd {
  mkdir $1 && cd $_;
}

function hist {
  history | les
}

###########
### git ###
###########

alias gst="git status" # this interfere with ghostscript program gs
alias gp="git pull"
alias gpu="git push"
alias gc="git commit -a -m"

# lazy git
function gl {
  if [ -z "$1" ]; then message="minor, message omitted"; else message="$1"; fi;
  git commit -a -m "$message";
  git push;
}

sortbed ()
{
    LC_ALL=C sort -k1,1 -k2,2n -T . $1
}
export -f sortbed

samnohead() { awk '!/^@/' $1; }
export -f samnohead

export TMPDIR=/mnt/isilon/zhoulab/tmp
export TEMP=/mnt/isilon/zhoulab/tmp

## fzf and z
. /mnt/isilon/zhoulab/labsoftware/z/z.sh

## re-define z with coupling with fzf, you need to install fzf (but needn't
## to invoke its key-binding or auto-completion)
## https://github.com/junegunn/fzf/wiki/examples#z
unalias z
z() {
  if [[ -z "$*" ]]; then        # when there is no argument
    cd "$(_z -l 2>&1 | fzf +s --tac | sed 's/^[0-9,.]* *//')"
  else                          # when there is argument
    if [[ $1 == -* ]]; then
      _z "$@"
    else
      cd "$(_z -l 2>&1 | fzf -q "$@" | sed 's/^[0-9,.]* *//')"
    fi
  fi
}

export WZSEQ_ENTRY=/mnt/isilon/zhoulab/labpipelines/entry/wzseq.sh
