#!/bin/bash

. /mnt/isilon/zhoulab/labtools/bashrc/chop/bashrc_hpc_zhoulab


alias Shold='parallel -j 10 "sha1sum /dev/zero" ::: {1..2}'


# change this in your own .bashrc
export HPCUSERNAME="zhouw3"
function qdelall {
   qstat | grep $HPCUSERNAME | awk '{split($1,a,".");print a[1]}' | xargs -I {} qdel {}
}

function checkref0 {
  samtools faidx $1 $2:$(($3-50))-$(($4+3));
}
function checkref16 {
  samtools faidx $1 $2:$(($3-3))-$(($4+50));
}

function sv {
  samtools view $1 | less -S
}

alias ta="tmux a" # tmux is still not as robust as screen
alias awk='awk -F"\t" -v OFS="\t"'

function dnarev {
  echo $1 | tr ATGC TACG | tr atgc TACG | rev;
}

# ## source .bashrc
alias sb="source ~/.bashrc"
