#!/bin/sh

alias rm='rm -i'

start_emacs() {
(exec emacsclient --alternate-editor="" -c "$@" $1 >/dev/null &)
}
alias emacs=start_emacs
start_emacsclient() {
(exec emacsclient $1 >/dev/null &)
}
alias emacsc=start_emacsclient
alias e=start_emacsclient
alias ec=start_emacsclient
alias ev=evince
alias lesslast="ls | tail -n1 | xargs less"

alias renamephotos='jhead -n%Y-%m-%d-%H.%M.%S *.jpg'

export HGEDITOR=emacsclient
export SVN_EDITOR=emacsclient
#export ALTERNATE_EDITOR=emacs EDITOR=emacsc VISUAL=emacsc

alias m='cd /media/ExternalDrivLarg/slowsync/2012-05-23-NCBI-Pal-56-pro-dataset'

alias l="less"

# alias e='LC_CTYPE="zh_CN.UTF-8" emacsclient'
alias e1='LC_CTYPE="zh_CN.UTF-8" emacsclient -t'
alias e2='LC_CTYPE="zh_CN.UTF-8" emacsclient -c'
## alias f='freeplane >& /dev/null &'
alias d='cd /home/wanding/Dropbox/'
alias d2='cd /home/wanding/Downloads/'
alias p1='cd /home/wanding/Dropbox/version_controled/svn.rice/wanding'
alias p2='cd /home/wanding/Dropbox/version_controled/svn.rice/wanding/dissertation'
alias reaa='cd /home/wanding/Dropbox/version_controled/bitbucket.org/reaa'

# cd aliases
alias wa='ssh wanding@wallace.cs.rice.edu'
alias sugar='ssh wz4@sugar.rice.edu'
alias es='/usr/bin/emacs --daemon'
alias m='caja .'
alias lp='lp -o sides=two-sided-long-edge -d phast '
alias gtsave='gnome-terminal --save-config=/home/wanding/Dropbox/config/gnometerminalsession'
alias update-tags="find . -type f -name '*py' | xargs createtags -o TAGS -a -l python"
alias paup=/home/wanding/Dropbox/softwares/PAUP/paup4b10-x86-linux/paup4b10-x86-linux
alias hi="festival --tts /home/wanding/Dropbox/study/thoughts/enticement_control.hinting;"
alias les="less -S"

# gene module project
alias infomap='/home/wanding/tools/infomap/Infomap-0.12.13/Infomap'
alias infotree2mod='python /home/wanding/Dropbox/scripts/python/infotree2mod.py'
alias uptrace='python /home/wanding/Dropbox/project_hgt/src2/2013_11_25_uptrace_match.py'
alias ll="ls -l"


export PATH=$PATH:/home/wanding/bin
export SCREENRC=/home/wanding/wzlib/screenrc/screenrc_hp

# for SCREEN
case $TERM in
  screen*)
    SCREENTITLE='\[\ek\e\\\]\[\ek\W\e\\\]'
    ;;
  *)
    SCREENTITLE=''
    ;;
esac

function prompt {
  local BLACK="\[\033[0;30m\]"
  local BLACKBOLD="\[\033[1;30m\]"
  local RED="\[\033[0;31m\]"
  local REDBOLD="\[\033[1;31m\]"
  local GREEN="\[\033[0;32m\]"
  local GREENBOLD="\[\033[1;32m\]"
  local YELLOW="\[\033[0;33m\]"
  local YELLOWBOLD="\[\033[1;33m\]"
  local BLUE="\[\033[0;34m\]"
  local BLUEBOLD="\[\033[1;34m\]"
  local PURPLE="\[\033[0;35m\]"
  local PURPLEBOLD="\[\033[1;35m\]"
  local CYAN="\[\033[0;36m\]"
  local CYANBOLD="\[\033[1;36m\]"
  local GREY="\[\033[00m\]"
  local WHITE="\[\033[0;37m\]"
  local WHITEBOLD="\[\033[1;37m\]"
  export PS1="$REDBOLD[\t]${SCREENTITLE}$GREY[$GREENBOLD\u@\h $YELLOWBOLD\w$GREY]\$ "
  # export PS1="$BLACKBOLD[\t]${SCREENTITLE}[\[\033[01;32m\]\u@\h \[\033[01;34m\]\w\[\033[00m\]]\$ "
  # export PS1="\n$BLACKBOLD[\t]$GREENBOLD \u@\h\[\033[00m\]:$BLUEBOLD\w\[\033[00m\] \\$ "
}

prompt


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_environvars ]; then
    . ~/.bash_environvars
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

alias les="less -S"
alias svt="python /home/wanding/svtyper/svtyper.py"
alias lc="wc -l"

### git ###

alias gs="git status"
alias gu="git pull"
alias gp="git pull"
alias gh="git push"
alias gc="git commit -a"
alias ga="git add"

# lazy git
function gl {

  if [ -z "$1" ]; then message="minor, message omitted"; else message="$1"; fi;
  git commit -a -m "$message";
  git push;
}
