#!/bin/sh

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi



### added from bashrc_mint
alias rm='rm -i'

start_emacs() {
(exec emacsclient --alternate-editor="" -c "$@" $1 >/dev/null &)
}
alias emacs=start_emacs
start_emacsclient() {
(exec emacsclient $1 >/dev/null &)
}
alias emacsc=start_emacsclient
alias e=start_emacsclient
alias ec=start_emacsclient
alias ev=evince
alias lesslast="ls | tail -n1 | xargs less"

alias renamephotos='jhead -n%Y-%m-%d-%H.%M.%S *.jpg'

HOME=/home/wanding
export HGEDITOR=emacsclient
export SVN_EDITOR=emacsclient
#export ALTERNATE_EDITOR=emacs EDITOR=emacsc VISUAL=emacsc
export PYTHONPATH=/home/wanding/wzlib/pyutils:/home/wanding/pythonlib/lib/python2.7/site-packages
export AWKPATH=$HOME/wzlib/awk

alias m='cd /media/ExternalDrivLarg/slowsync/2012-05-23-NCBI-Pal-56-pro-dataset'

alias l="less"

# alias e='LC_CTYPE="zh_CN.UTF-8" emacsclient'
alias e1='LC_CTYPE="zh_CN.UTF-8" emacsclient -t'
alias e2='LC_CTYPE="zh_CN.UTF-8" emacsclient -c'
## alias f='freeplane >& /dev/null &'
alias d='cd /home/wanding/Dropbox/'
alias d2='cd /home/wanding/Downloads/'
alias p1='cd /home/wanding/Dropbox/version_controled/svn.rice/wanding'
alias p2='cd /home/wanding/Dropbox/version_controled/svn.rice/wanding/dissertation'
alias reaa='cd /home/wanding/Dropbox/version_controled/bitbucket.org/reaa'

# cd aliases
alias wa='ssh wanding@wallace.cs.rice.edu'
alias sugar='ssh wz4@sugar.rice.edu'
alias es='/usr/bin/emacs --daemon'
alias m='caja .'
#alias n="nautilus ."
alias lp='lp -o sides=two-sided-long-edge -d phast '
alias gtsave='gnome-terminal --save-config=/home/wanding/Dropbox/config/gnometerminalsession'
alias update-tags="find . -type f -name '*py' | xargs createtags -o TAGS -a -l python"
alias paup=/home/wanding/Dropbox/softwares/PAUP/paup4b10-x86-linux/paup4b10-x86-linux
alias hi="festival --tts /home/wanding/Dropbox/study/thoughts/enticement_control.hinting;"
alias les="less -S"

# gene module project
alias infomap='/home/wanding/tools/infomap/Infomap-0.12.13/Infomap'
alias infotree2mod='python /home/wanding/Dropbox/scripts/python/infotree2mod.py'
alias uptrace='python /home/wanding/Dropbox/project_hgt/src2/2013_11_25_uptrace_match.py'
alias ll="ls -l"

function dnarev {
  echo $1 | tr ATGC TACG | rev;
}

export PATH=$PATH:/home/wanding/bin
export PATH=/home/wanding/anaconda2/bin:$PATH
export SCREENRC=/home/wanding/wzlib/screenrc/screenrc_hp

# for SCREEN
case $TERM in
  screen*)
    SCREENTITLE='\[\ek\e\\\]\[\ek\W\e\\\]'
    ;;
  *)
    SCREENTITLE=''
    ;;
esac

function prompt {
  local BLACK="\[\033[0;30m\]"
  local BLACKBOLD="\[\033[1;30m\]"
  local RED="\[\033[0;31m\]"
  local REDBOLD="\[\033[1;31m\]"
  local GREEN="\[\033[0;32m\]"
  local GREENBOLD="\[\033[1;32m\]"
  local YELLOW="\[\033[0;33m\]"
  local YELLOWBOLD="\[\033[1;33m\]"
  local BLUE="\[\033[0;34m\]"
  local BLUEBOLD="\[\033[1;34m\]"
  local PURPLE="\[\033[0;35m\]"
  local PURPLEBOLD="\[\033[1;35m\]"
  local CYAN="\[\033[0;36m\]"
  local CYANBOLD="\[\033[1;36m\]"
  local GREY="\[\033[00m\]"
  local WHITE="\[\033[0;37m\]"
  local WHITEBOLD="\[\033[1;37m\]"
  export PS1="$REDBOLD[\t]${SCREENTITLE}$GREY[$GREENBOLD\u@\h $YELLOWBOLD\w$GREY]\$ "
  # export PS1="$BLACKBOLD[\t]${SCREENTITLE}[\[\033[01;32m\]\u@\h \[\033[01;34m\]\w\[\033[00m\]]\$ "
  # export PS1="\n$BLACKBOLD[\t]$GREENBOLD \u@\h\[\033[00m\]:$BLUEBOLD\w\[\033[00m\] \\$ "
}

prompt


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep -n --color=auto'
    alias fgrep='fgrep -n --color=auto'
    alias egrep='egrep -n --color=auto'
fi

# Alias definitions.
if [ -f ~/.bash_environvars ]; then
    . ~/.bash_environvars
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

alias les="less -S"
alias svt="python /home/wanding/svtyper/svtyper.py"
alias lc="wc -l"

### git ###

alias gs="git status"
alias gu="git pull"
alias gp="git pull"
alias gh="git push"
alias gc="git commit -a"
alias ga="git add"

# lazy git
function gl {

  if [ -z "$1" ]; then message="minor, message omitted"; else message="$1"; fi;
  git commit -a -m "$message";
  git push;
}


# source /home/wanding/Downloads/EMAN2/eman2.bashrc

function findc {
  symbol=$1;
  find . -regex '.*\.\(h\|c\)' -exec grep $symbol {} -H \;
}

function etagsc {
  find . -regex '.*\.\(c\|h\)' | xargs etags
}
