#+STARTUP: indent
#+TAGS: memorize(a)

* words and sentences

Where would I have got it from? Why would I have known it?

Don't come any closer!

I don't intend on wasting it.

Where do you think you are going? What do you think you are doing? What makes you think that ...

Last but foremost, our IHM approach lends itself in a straightforward manner to hypothesis generation.

What am I to do with these?

It's a sensitive matter and Richard's asked for complete discretion.

I will honor your wish.

I know this doesn't please you.

The reader is cautioned that this nomenclature connotes neither the size nor functional characterization of these genomic elements
HERE
We can work on this first, meanwhile we can work on the technical contents.

Right now, there isn't much of a limit on interactive jobs.

To restate this: what is the probability distribution of the different coverage values on a set after X randomly, independently selected elements of the set?

I'm not surprised that somebody orchestrating such a large illegal endeavor like The Pirate Bay had a built-in contingency plan for when he was arrested. I am a little surprised that the police would let him use his own phone though.

I'd imagine for the cops it's a lot easier to have you use your own phone than try to figure out what the number is.

It is funny that people would think punishing someone for their ethics which happen to be primarily based on the idea of freedom, would change their view. If anything it would further radicalize them, or at least temper their resolve.

<what app did he use?
>what kind of app could you do this with?

Dead man switch. I've seen a number of them over the years. I think one of them would regularly send you emails, and if you didn't respond within a set time, it would carry out whatever function you set it up to do.

It wouldn't be nearly as expensive or invasive and gains a lot of ground in the realm of reasonability.

Absolutely brilliant! Now a toast to Peter Sunde as I watch the new episode of Game of Thrones.

There is a special place in hell for these people (assuming you believe in that sort of thing).

Never forget that the lowest bidder made your weapon.

The easiest way is always mined.

The important things are always simple. The simple things are always hard.

If the enemy is in range, so are you.

Anything you do can get you shot, including doing nothing.

** If it's stupid but it works, it's not stupid
** Don't look conspicuous - it draws fire.
** come about, race on,
My mind raced on: Was this a laboratory model of human helplessness, one that could be used to understand how it comes about
** how ... operate in cell
** quite an undertaking
** totaling ...
The numbers assigned to nodes are the allelic copy numbers (totaling
20, the number of segments)
** a perspective of ... as ...
In 1976, Peter Nowell3 published a landmark perspective on cancer as an evolutionary process that is driven by stepwise, somatic-cell mutations with sequential, subclonal selection.
** paradigm, stemming from, hematopoietic malignancy
The paradigm stemming from the study of hematopoietic malignancies and sarcomas is that cancers are of monoclonal origin
** Of special importance is ...
Of special importance are changes that occur early during malignant transformation because they may result in oncogene addiction and thus represent promising targets for therapeutic intervention.
** inadvertently
Therapeutic intervention may destroy cancer clones and erode their habitats, but it can also inadvertently provide a potent selective pressure for the expansion of resistant variants.
** harbor acquired aberrations, neoplasia, cytogenetic
All or almost all neoplasias subjected to systematic cytogenetic scrutiny have been found to harbor acquired chromosomal aberrations.
** a phase-informative site
** set the stage for
Early mathematical modeling of cancer, by Armitage and Doll, set the stage for the future development of the somatic evolutionary theory of cancer.
** determined solely by, but also by
Successful outgrowth of tumours and eventual metastasis is not determined solely by genetic alterations in tumour cells, but also by the fitness advantage such mutations confer in a given environment.
** a population of mutant cells, called a clone
In this way, a population of mutant cells, called a clone, can expand in the neoplasm. Clonal expansion is the signature of natural selection in cancer.
** afflict
what afflicted those dogs
** our method will be advantageous
** not the solution to the problem, xxx is the problem
In this case, government is not the solution to the problem. Government is the problem.
** a conceptual extension of xxx to xxx 
The method developed here is a conceptual extension of this concept to the SFS
** any specifics coming out of xxx
but I don't remember any specifics coming out of it.
** in this regard,
** obstruct the advance of xxx
** speaking of this,
** not an expert of, did not provide [] to help me see :memorize:
I am not an expert in either of these specific systems, but the write up did not provide enough background to help me see what was gained from the modeling exercise.
** do not mean that xxx is wrong, only that
I do not mean that the authors are wrong in this case, only that they did not provide information to show the readers that fewer parameters are appropriate here. 
** versed in xxx
This addition would make the manuscript more clear for people that are less versed in this type of modeling.
** corroborate this assertion
I can't corroborate this assertion.
** despite the long-standing recognition that
** the remarkable tapestry of
Here we describe the remarkable tapestry of biological, evolutionary, and therapeutic insights that have emerged from systematic cancer genome characterization.
** at its simplest ...
What it means to be ...? At its simplest, it means ...
** of assistance
Let me know if I can be of assistance.
* TODO other uncompiled
they also expect the cost of genomic studies to plummet, with new technologies just over the horizon.

whereas others thought that cancers were too hopelessly complicated to yield to systematic analysis.

Such expansion in the copy number is considered a partial gain, *as opposed to* a complete gain whose start state is 0

Two gene families (COG3319 and COG2931) which MUSCLE does not *accomodate*

emphasis must be placed on ...

besides --> additionally

metabolism does not function in isolation from the other components of the cell.

Other than --> *Apart from* these practical purposes,

I'll highlight relevant prior work published by Sharan et al. (including Trey Ideker and Richard Karp) in JCB *circa* 2005

changed our life immeasurably, for good.

to redefine the SMILE language in a public manner.

The HTC One’s “UltraPixel” camera sounds like marketing palaver but actually makes for an impressive shooter. In each situation we tested, the HTC One’s camera performed *on par with* — or better than — the competition. Whether it beats out the excellent Lumia 920 might come down to personal preference, but there’s no denying the HTC One’s camera exhibits such great low-light performance

High-throughput sequencing platforms are emerging as the heir to the ubiquitous microarray, 

These assays have the potential to accelerate biological discovery as comprehensive analyses of genomes, meta-genomes, transcriptomes and metabolomes becomes increasingly inexpensive and routine. 

experimental design *has a large impact* on what algorithms and pipelines are a good fit

At the same time, advances in high-throughput mass spectrometry are making it possible to investigate the outcomes of differential gene expression through simultaneous measurement of metabolites, transcriptomes, and epigenomes.

Interpreting these vast data sets requires user-friendly but powerful visualization and modeling tools that promote exploration, analysis, and discovery.

Databases are current as of October 2011

Genome-scale metabolic networks can now be reconstructed based on
annotated genomic data *augmented with* biochemical and physiological
information about the organism.

who are increasingly voicing concerns for ...

i'm noticing a phenomenon

the converging, so to speak, ...

whatever the context may be,

while the ambulances rushed in, sirens wailing, to reach the wounded, Afghan soldiers in full body armor quickly cordoned off the area.
I saw dead bodies and wounded victims lying everywhere.

for better, for worse, for richer, for poorer, in sickness and in health, until death do us part.

 I'm here once again on the pristine little Italian island of Giglio, made famous not for its beauty, but for the tragedy on its shores.

Based on these features, ORFans are not attributable to errors in gene annotation, limitations of current databases, or to failure of methods for detecting homology. *Rather*, ORFans in the genomes of free-living microorganisms apparently derive from bacteriophage and occasionally become established by assuming roles in key cellular functions.

This theory is most clearly *manifested* in pathogenicity and ecological islands, which are contiguous sets of genes acquired through HGT that form genomic islands of atypical composition

*It would be difficult to overstate the urgent need* for China to emulate South Korea in eliminating sex-biased abortion and neglect. 

The American frontier earned its "Wild West" reputation for lawlessness because its towns overflowed with men, yet marriageable women were *vanishingly rare*.

Throughout history, a surplus of young men often *heralded* violence. 

Young men with poor prospects of ever starting a family spell danger to themselves and to their societies. 

This story of the Nien Rebellion *foreshadows* one of the biggest issues that China will face in coming decades: the dramatic excess of young men.

We discuss the need for additional theory and genomic level information to *disentangle* the roles of evolutionary mechanisms operating within and amongst individuals in driving the dynamics of gene distributions.

what about you?

The analysis of whole genomes has *reinvigorated* its investigation.

The advancement of sequencing technologies has taken phylogenetic analysis to a new height.

These effects can be pronounced in the primates, owing to large
ancestral effective population sizes relative to the intervals between speciation events.

Does it upset you that ?

Despite the outrage *sparked* by a joke about the Holocaust, comedian Joan Rivers said she had nothing to apologize for.

*As like I said*, I work two jobs, trying to support my family.

I worry that I might feel like a wilting flower, is all, who never blossomed to her full potential, at least in a sexual realm. 

you are actually into it as much as he was

after this encounter on this special day,

it also implies that 

all that stuff, or information, *whatever you want to call it*, isn't out there...

you said, no, this is not the way for me to go, right?

can you imagine, how much it must have hurt Mr Alexandre, when you stuck that knife right into his chest, that really must have hurt, right

If you torture the data enough, nature will always confess.

Among the issues about which lawmakers showed greatest concern was the impact of the looming automatic budget cuts, or sequestration.

the timing of the last-minute meeting has been widely criticized - but with most members of Congress out of town, *the likelihood* of Washington's top brass reaching a deal Friday to avert the cuts is *slim*.

Environmental and political issues created by dependence on fossil fuels, coupled with diminishing petroleum resources, have *sparked a quest for* novel renewable sources of energy and chemicals

Metabolism *encompasses* the biochemical basis of life and as such spans all biological disciplines.

Gene loss cannot be unequivocally inferred for a species if one does not have the complete genome.

The converse is also true—certain genomic studies are greatly improved by using evolutionary analysis.

which is coined "module"

I understand your apprehension.

feature
characterize
possess
mediate

The game-changing output from these large-scale collaborative efforts is radically *transforming* the way cancer science is conducted.

At the same time, these efforts are uncovering a staggering level of genome complexity in cancer, making it clear that effective translation of this newfound genomic knowledge into cancer therapeutics and diagnostics will require not only comprehensive cataloguing

Note that *if desired*, these steps can be replaced by matching gene sequences against a database of known structural or functional protein domains to simultaneously detect the domain boundaries and domain families. 

RIATA-HGT may overestimate the optimal number of HGT events; empirical performance, however, shows that such overestimation is very *mild*

the fixation of genes horizontally transferred is not a *rampant* phenomenon

Despite the sophisticated underlying models in these methods, a common assumption is to consider a gene as evolving as a single unit.

special algorithms called “reconciliation methods” can be used to determine how the gene tree fits inside, *or rather “reconciles,”* to the species tree

Accumulating prokaryotic gene and genome sequences reveal that the exchange of genetic information through both homology-dependent recombination and horizontal (lateral) gene transfer (HGT) is far more important, in quantity and quality, than *hitherto* imagined.

take into consideration --> account for

The traditional view, that prokaryotic evolution can be understood *primarily* in terms of clonal divergence and periodic selection, must *be augmented to* *embrace* gene exchange as a creative force, itself responsible for much of the pattern of similarities and differences we see between prokaryotic microbes.

This method is of particular interest for studying genes that *exhibit* no, or only remote, homologies with already well-characterized proteins.

Microbes occupy almost every habitable niche in the biosphere, *highlighting* their enormous capability for adaptation and survival. 

This the acquisition of foreign genes

highlights the promise
outlines
discuss
allow us to consider

characterize
develop

provide
inform: Modelling efforts should in turn inform data collection, providing species of interest.

accumulate

pose huge challenge to
many problem arise from xxx

a must go hand-in-hand with b
facilitating ...

AAA is considered a touchstone of our understanding
investigate

tremendous potential
overarching goal

XXX is an exciting frontier

AA has revolutionized BB

aim to 

capture

forseeable future

hold great promise

address question

something can be addressed only by considering XXX

acknowledging XXXX

something is uniquely apt for studying ...


is scarce and something is still needed
be bound to lead to exciting discoveries

fundamentally system-level question
, as a whole, 

let's aim for next friday

In the coming months, Mr. Rehn must decide whether to recommend punishing countries for missing their targets, possibly leading to large fines, or to offer them leniency.

We all add to our memories of childhood appropriate bits of what we have read or heard since then.

If a first, unpublicized marriage might lay to rest one contentious issue, there are others.

The wardens, driving in two different vehicles, chased Dorner and a gun battle ensued.

Comparative analyses of the human microbiome have revealed substantial variation in species and gene composition associated with a variety of disease states but may fall short of providing a comprehensive understanding of the impact of this variation on the community and on the host

switch → migrate

Any minute? Some people live a lifetime in a minute

What little we have, we will share with her too.

l am sorry to hear about your troubles, but, be that as it may, you still must carry out your responsibilities. Be that as it may, I still cannot help you. 
He certainly was under pressure at the time. Be that as it may, he was still wrong to react in the way that he did.

The characterization of tumor bioenergetics profile necessitates tumor excision and both molecular
and functional analyses in a microenvironment that mimics the tumor milieu.

We compared the difference in community structures against the difference in modularities and the genetic distance, to investigate the correlation, or lack thereof, among the three.


3. 

2. 

1.
* russian
осень
дождь

